import { HeroSection } from "@/components/content/HeroSection";
import { ClientsSection } from "@/components/content/Clients";
import { ContactUs } from "@/components/content/ContactUs";
import { Features } from "@/components/content/Features";
import { HowItWork } from "@/components/content/HowItWork";
import { Pricing } from "@/components/content/Pricing";
import { Testimonials } from "@/components/content/Testimonials";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Some SaaS App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="">
      <HeroSection />
      <ClientsSection />
      <Features />
      <HowItWork />
      <Pricing />
      <Testimonials />
      <ContactUs />
    </main>
  );
}
